### ISSUE TITLE
Add tests in the package

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#45]
Next very important task ! 

* Add and improve manual test because it is useful to have at least those
* Add non regression test where we can to have some coverage and a better fail safe.

**Comment by RLesur** [comment]
I have configured Chrome in Travis CI.
We can now run test with or without headless Chrome.

**Comment by RLesur** [comment]
FYI, when Chrome is required to run some test files, R CMD check fails if `HEADLESS_CHROME` has not been defined.
This is fixed in https://github.com/RLesur/crrri/commit/f86926808c56a333294037401937cb2f8af8f6e4

By now, if a test file needs Chrome to run, it must contain the string `needs-chrome` in its file name.

**Comment by cderv** [comment]
Can't we add a testthat helper `skip_if_chrome_not_available` ? 
We would add this inside each test that can't run without chrome. 

If ok I will add that, 

```r
skip_if_not_chrome <- function() {
  if (nzchar(Sys.getenv("HEADLESS_CHROME"))) {
    return(invisible(TRUE))
  }
  testthat::skip("Chrome is required to run this test and is not available.")
}
```

**Comment by cderv** [comment]
I will also complete the structure of testthat test by adding setup and teardown script I think. This will be very useful considering we need to open and close connection with chrome. I'll do a PR for that once you've seen the previous one :)

**Comment by cderv** [comment]
We begin to have a good coverage. Still missing some files like 

- [ ] utils.R
